services:
  mkdocs:
    image: squidfunk/mkdocs-material
    restart: always
    container_name: mkdocs
    ports:
      - 8010:8000
    volumes:
      - "${PWD}:/docs"
      - "/mkdocs.yml:/mkdocs.yml"
