site_name: wikiey
theme:
  name: material
  font:
    text: Noto Sans JP
    code: Inconsolata
  palette:
    - scheme: default
      primary: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
